

DOT.ANGULAR = {

    /**
     * Return the browser-side JavaScript code to enable Angular-Integration
     * and register the DOTjs
     *
     * @returns {string}
     */
    printAngularInit: function () {
        var initCode = "";
        initCode += "\n\n<!-- Auto-generated by DOT.ANGULAR.printAngularInit() -->";
        initCode += "\n<script language=\"JavaScript\">\n";
        initCode += DOT.fileGetContents(__DIR__ + "/../_shared/toolkit.js");
        initCode += DOT.fileGetContents(__DIR__ + "/../_browser/dot.js");
        initCode += DOT.fileGetContents(__DIR__ + "/browser/angular-dot.js");
        initCode += "\n</script>\n";
        initCode = initCode.replace("$$$ENV$$$", JSON.stringify(DOT.ENV));
        DOT.print(initCode);
    }
};